name: pages-build-deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Ensure build steps generate output to './build' directory
      - name: Build project
        run: npm run build  # Example build command, replace as necessary

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-${{ github.run_id }}
          path: ./build  # Ensure this path is correct

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.run_id }}
